# Run with: docker-compose up --build
version: '3'
services:
  student_service:
    # This uses the Dockerfile to build the image in the current directory (.)
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
    ports:
      - "8080:8080"
  
  # Also run mongodb as a separate service using the image mongo:4
  mongo:
    restart: unless-stopped
    image: mongo:4
    ports:
      - "27017:27017"